### ISSUE TITLE
Missing value error

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValTool_Tutorial#124]
There is a missing value error for in these 2 code snippets:
https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/05-preprocessor.md#exercise-adding-more-preprocessor-steps
https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/05-preprocessor.md#example

This is my recipe:

```yaml
# ESMValTool
# recipe_example.yml
---
documentation:
  description: Demonstrate basic ESMValTool example

  authors:
    - demora_lee
    - mueller_benjamin
    - swaminathan_ranjini

  maintainer:
    - demora_lee

  references:
    - demora2018gmd
    # Some plots also appear in ESMValTool paper 2.

  projects:
    - ukesm

datasets:
  - {dataset: HadGEM2-ES, project: CMIP5, exp: historical, mip: Omon, ensemble: r1i1p1, start_year: 1859, end_year: 2005}

preprocessors:
  prep_timeseries: # For 0D fields
    annual_statistics:
      operator: mean
    area_statistics:
      operator: mean
    depth_integration:

diagnostics:
  # --------------------------------------------------
  # Time series diagnostics
  # --------------------------------------------------
  diag_timeseries_temperature:
    description: simple_time_series
    variables:
      timeseries_variable:
        short_name: thetaoga
        preprocessor: prep_timeseries
    scripts:
      timeseries_diag:
        script: ocean/diagnostic_timeseries.py
```

Stack trace:

```
2020-08-07 13:38:55,570 UTC [9014] ERROR   Program terminated abnormally, see stack trace below for more information
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 730, in _run_task
    output_files = task.run()
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 242, in run
    self.output_files = self._run(input_files)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/preprocessor/__init__.py", line 428, in _run
    product.apply(step, self.debug)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/preprocessor/__init__.py", line 296, in apply
    self.cubes = preprocess(self.cubes, step, **self.settings[step])
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/preprocessor/__init__.py", line 241, in preprocess
    result.append(_run_preproc_function(function, item, settings))
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/preprocessor/__init__.py", line 224, in _run_preproc_function
    return function(items, **kwargs)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/preprocessor/_volume.py", line 307, in depth_integration
    depth = cube.coord(axis='z')
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/iris/cube.py", line 1497, in coord
    raise iris.exceptions.CoordinateNotFoundError(msg)
iris.exceptions.CoordinateNotFoundError: 'Expected to find exactly 1  coordinate, but found none.'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 407, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 98, in process_recipe
    recipe.run()
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 1358, in run
    run_tasks(self.tasks,
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 650, in run_tasks
    _run_tasks_parallel(tasks, max_parallel_tasks)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 695, in _run_tasks_parallel
    _copy_results(task, running[task])
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_task.py", line 718, in _copy_results
    task.output_files, updated_products = future.get()
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
iris.exceptions.CoordinateNotFoundError: 'Expected to find exactly 1  coordinate, but found none.'

```

**Comment by stefsmeets** [comment]
Actually, maybe it is missing some coordinate value, and not the depth value.

**Comment by SarahAlidoost** [comment]
@stefsmeets thanks. The error caused by missing data for the variable `thetao' from CMIP5. PR #130 will fix this issue.
