### ISSUE TITLE
RecipeError: Missing data in episode 5

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValTool_Tutorial#126]
I'm trying to run the examples in episode 5 (https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/05-preprocessor.md#adding-different-datasets-for-different-variables), but I get a missing data error.

Here is my recipe:
```yaml
# ESMValTool
# recipe_example.yml
---
documentation:
  description: Demonstrate basic ESMValTool example

  authors:
    - demora_lee
    - mueller_benjamin
    - swaminathan_ranjini

  maintainer:
    - demora_lee

  references:
    - demora2018gmd
    # Some plots also appear in ESMValTool paper 2.

  projects:
    - ukesm


datasets:
  - {dataset: UKESM1-0-LL, project: CMIP6, exp: historical,
     ensemble: r1i1p1f2} #common to both variables discussed below

preprocessors:
  prep_regrid: # regrid to get all data to the same resolution
    regrid:    #apply the preprocessor to regrid
      target_grid: 2.5x2.5 # target resolution
      scheme: linear  #how to interpolate for regridding

diagnostics:
  # --------------------------------------------------
  # Simple diagnostic to illustrate use of different
  # datasets for different variables
  # --------------------------------------------------
  diag_diff_datasets:
    description: diff_datasets_for_vars
    variables:
      pr:  # first variable is precipitation
        preprocessor: prep_regrid
        mip: Amon
        grid: gn #can change for variables from the same model
        start_year: 1970
        end_year: 2000 # start and end years for a 30 year period,
                       # we assume this is common and exists for all
                       # model and obs data
        additional_datasets:
          - {dataset: GPCP-SG, project: obs4mips, level: L3,
             version: v2.2, tier: 1} #dataset specific to this variable
      tas: # second variable is surface temperature
        preprocessor: prep_regrid
        mip: Amon
        grid: gn #can change for variables from the same model
        start_year: 1970  #some 30 year period
        end_year: 2000
        additional_datasets:
          - {dataset: HadCRUT4, project: OBS, type: ground,
             version: 1, tier: 2} #dataset specific to the temperature variable
    scripts: null
```

This is the tracelog:

```2020-08-11 09:02:49,794 UTC [12762] INFO    Using config file ~/.esmvaltool/config-user.yml
2020-08-11 09:02:49,794 UTC [12762] INFO    Writing program log files to:
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_2_20200811_090249/run/main_log.txt
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_2_20200811_090249/run/main_log_debug.txt
2020-08-11 09:02:49,794 UTC [12762] INFO    Starting the Earth System Model Evaluation Tool v2.0.0 at time: 2020-08-11 09:02:49 UTC
2020-08-11 09:02:49,794 UTC [12762] INFO    ----------------------------------------------------------------------
2020-08-11 09:02:49,794 UTC [12762] INFO    RECIPE   = /home/stef/esmvaltool_tutorial/recipe_example_multi_preprocessors_2.yml
2020-08-11 09:02:49,795 UTC [12762] INFO    RUNDIR     = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_2_20200811_090249/run
2020-08-11 09:02:49,795 UTC [12762] INFO    WORKDIR    = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_2_20200811_090249/work
2020-08-11 09:02:49,795 UTC [12762] INFO    PREPROCDIR = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_2_20200811_090249/preproc
2020-08-11 09:02:49,795 UTC [12762] INFO    PLOTDIR    = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_2_20200811_090249/plots
2020-08-11 09:02:49,795 UTC [12762] INFO    ----------------------------------------------------------------------
2020-08-11 09:02:49,795 UTC [12762] INFO    Running tasks using at most 8 processes
2020-08-11 09:02:49,795 UTC [12762] INFO    If your system hangs during execution, it may not have enough memory for keeping this number of tasks in memory.
2020-08-11 09:02:49,795 UTC [12762] INFO    If you experience memory problems, try reducing 'max_parallel_tasks' in your user configuration file.
2020-08-11 09:02:49,807 UTC [12762] INFO    Creating tasks from recipe
2020-08-11 09:02:49,807 UTC [12762] INFO    Creating tasks for diagnostic diag_diff_datasets
2020-08-11 09:02:49,807 UTC [12762] INFO    Creating preprocessor task diag_diff_datasets/pr
2020-08-11 09:02:49,807 UTC [12762] INFO    Creating preprocessor 'prep_regrid' task for variable 'pr'
2020-08-11 09:02:49,808 UTC [12762] INFO    Using input files for variable pr of dataset UKESM1-0-LL:
/home/stef/default_inputpath/pr_Amon_UKESM1-0-LL_historical_r1i1p1f2_gn_195001-201412.nc
2020-08-11 09:02:49,812 UTC [12762] INFO    Using input files for variable pr of dataset GPCP-SG:

2020-08-11 09:02:49,812 UTC [12762] ERROR   No input files found for variable {'preprocessor': 'prep_regrid', 'mip': 'Amon', 'grid': 'gn', 'start_year': 1970, 'end_year': 2000, 'variable_group': 'pr', 'short_name': 'pr', 'diagnostic': 'diag_diff_datasets', 'dataset': 'GPCP-SG', 'project': 'obs4mips', 'level': 'L3', 'version': 'v2.2', 'tier': 1, 'recipe_dataset_index': 1, 'alias': 'obs4mips', 'standard_name': 'precipitation_flux', 'long_name': 'Precipitation', 'units': 'kg m-2 s-1', 'modeling_realm': [], 'frequency': 'mon'}
2020-08-11 09:02:49,812 UTC [12762] ERROR   Looked for files matching ['pr_GPCP-SG_L3_v2.2_*.nc'], but did not find any existing input directory
2020-08-11 09:02:49,812 UTC [12762] ERROR   Set 'log_level' to 'debug' to get more information
2020-08-11 09:02:50,796 UTC [12762] INFO    Maximum memory used (estimate): 0.0 GB
2020-08-11 09:02:50,797 UTC [12762] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2020-08-11 09:02:50,797 UTC [12762] ERROR   Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 407, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 94, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 71, in read_recipe_file
    return Recipe(raw_recipe,
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 949, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 1297, in initialize_tasks
    task = _get_preprocessor_task(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 915, in _get_preprocessor_task
    task = _get_single_preprocessor_task(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 774, in _get_single_preprocessor_task
    products = _get_preprocessor_products(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 740, in _get_preprocessor_products
    ancestors = _get_ancestors(variable, config_user)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 552, in _get_ancestors
    check.data_availability(input_files, variable, dirnames, filenames)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe_checks.py", line 119, in data_availability
    raise RecipeError("Missing data")
esmvalcore._recipe_checks.RecipeError: Missing data
```

**Comment by stefsmeets** [comment]
It appears that I'm missing `pr_GPCP-SG_L3_v2.2_*.nc`

Is this related to #123? Or is it an exercise for the reader to find these data?

**Comment by stefsmeets** [comment]
I get the same for (https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/05-preprocessor.md#creating-variable-groups) which looks for `OBS_HadCRUT4_ground_1_Amon_tas[_.]*nc`.

Recipe:
```yaml
# ESMValTool
# recipe_example.yml
---
documentation:
  description: Demonstrate basic ESMValTool example

  authors:
    - demora_lee
    - mueller_benjamin
    - swaminathan_ranjini

  maintainer:
    - demora_lee

  references:
    - demora2018gmd
    # Some plots also appear in ESMValTool paper 2.

  projects:
    - ukesm

preprocessors:
 prep_mmm:
   custom_order: true
   regrid:
     target_grid: 2.5 x 2.5
     scheme: linear
   multi_model_statistics:
     span: full
     statistics: [mean, median]

 prep_obs:
   mask_landsea:
     mask_out: sea
   regrid:
     target_grid: 2.5 x 2.5
     scheme: linear

# note that there is no field called datasets anymore
# note how multiple ensembles are added by using (1:4)
cmip5_datasets: &cmip5_datasets
 - {dataset: CanESM2, ensemble: "r(1:4)i1p1", project: CMIP5}
 - {dataset: MPI-ESM-LR, ensemble: "r(1:2)i1p1", project: CMIP5}

cmip6_datasets: &cmip6_datasets
 - {dataset: UKESM1-0-LL, ensemble: "r(1:4)i1p1f2", grid: gn, project: CMIP6}
 - {dataset: CanESM5, ensemble: "r(1:4)i1p2f1", grid: gn, project: CMIP6}

diagnostics:

 diag_variable_groups:
   description: Demonstrate the use of variable groups.
   variables:
     tas_cmip5: &variable_settings # need a key name for the grouping
       short_name: tas # specify variable to look for
       preprocessor: prep_mmm
       mip: Amon
       exp: historical
       start_year: 2000
       end_year: 2005
       tag: TAS_CMIP5 #tag is optional if you are using these settings just once
       additional_datasets: *cmip5_datasets
     tas_obs:
       <<: *variable_settings
       preprocessor: prep_obs
       tag: TAS_OBS
       additional_datasets:
         - {dataset: HadCRUT4, project: OBS, type: ground, version: 1, tier: 2}
     tas_cmip6:
       <<: *variable_settings
       tag: TAS_CMIP6
       additional_datasets: *cmip6_datasets #nothing changes from cmip5 except the data set
   scripts: null
```

Tracelog:
```
2020-08-11 09:06:57,665 UTC [12788] INFO    Using config file ~/.esmvaltool/config-user.yml
2020-08-11 09:06:57,665 UTC [12788] INFO    Writing program log files to:
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/run/main_log.txt
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/run/main_log_debug.txt
2020-08-11 09:06:57,666 UTC [12788] INFO    Starting the Earth System Model Evaluation Tool v2.0.0 at time: 2020-08-11 09:06:57 UTC
2020-08-11 09:06:57,666 UTC [12788] INFO    ----------------------------------------------------------------------
2020-08-11 09:06:57,666 UTC [12788] INFO    RECIPE   = /home/stef/esmvaltool_tutorial/recipe_example_multi_preprocessors_3.yml
2020-08-11 09:06:57,666 UTC [12788] INFO    RUNDIR     = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/run
2020-08-11 09:06:57,666 UTC [12788] INFO    WORKDIR    = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/work
2020-08-11 09:06:57,666 UTC [12788] INFO    PREPROCDIR = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/preproc
2020-08-11 09:06:57,666 UTC [12788] INFO    PLOTDIR    = /home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/plots
2020-08-11 09:06:57,666 UTC [12788] INFO    ----------------------------------------------------------------------
2020-08-11 09:06:57,666 UTC [12788] INFO    Running tasks using at most 8 processes
2020-08-11 09:06:57,667 UTC [12788] INFO    If your system hangs during execution, it may not have enough memory for keeping this number of tasks in memory.
2020-08-11 09:06:57,667 UTC [12788] INFO    If you experience memory problems, try reducing 'max_parallel_tasks' in your user configuration file.
2020-08-11 09:06:57,681 UTC [12788] INFO    Creating tasks from recipe
2020-08-11 09:06:57,681 UTC [12788] INFO    Creating tasks for diagnostic diag_variable_groups
2020-08-11 09:06:57,681 UTC [12788] INFO    Creating preprocessor task diag_variable_groups/tas_cmip5
2020-08-11 09:06:57,681 UTC [12788] INFO    Creating preprocessor 'prep_mmm' task for variable 'tas'
2020-08-11 09:06:57,682 UTC [12788] INFO    Using input files for variable tas of dataset CanESM2:
/home/stef/default_inputpath/tas_Amon_CanESM2_historical_r1i1p1_185001-200512.nc
2020-08-11 09:06:57,750 UTC [12788] INFO    Using input files for variable tas of dataset CanESM2:
/home/stef/default_inputpath/tas_Amon_CanESM2_historical_r2i1p1_185001-200512.nc
2020-08-11 09:06:57,752 UTC [12788] INFO    Using input files for variable tas of dataset CanESM2:
/home/stef/default_inputpath/tas_Amon_CanESM2_historical_r3i1p1_185001-200512.nc
2020-08-11 09:06:57,755 UTC [12788] INFO    Using input files for variable tas of dataset CanESM2:
/home/stef/default_inputpath/tas_Amon_CanESM2_historical_r4i1p1_185001-200512.nc
2020-08-11 09:06:57,757 UTC [12788] INFO    Using input files for variable tas of dataset MPI-ESM-LR:
/home/stef/default_inputpath/tas_Amon_MPI-ESM-LR_historical_r1i1p1_185001-200512.nc
2020-08-11 09:06:57,760 UTC [12788] INFO    Using input files for variable tas of dataset MPI-ESM-LR:
/home/stef/default_inputpath/tas_Amon_MPI-ESM-LR_historical_r2i1p1_185001-200512.nc
2020-08-11 09:06:57,765 UTC [12788] INFO    PreprocessingTask diag_variable_groups/tas_cmip5 created. It will create the files:
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/preproc/diag_variable_groups/tas_cmip5/CMIP5_CanESM2_Amon_historical_r2i1p1_tas_2000-2005.nc
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/preproc/diag_variable_groups/tas_cmip5/CMIP5_MPI-ESM-LR_Amon_historical_r1i1p1_tas_2000-2005.nc
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/preproc/diag_variable_groups/tas_cmip5/CMIP5_CanESM2_Amon_historical_r4i1p1_tas_2000-2005.nc
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/preproc/diag_variable_groups/tas_cmip5/CMIP5_CanESM2_Amon_historical_r3i1p1_tas_2000-2005.nc
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/preproc/diag_variable_groups/tas_cmip5/CMIP5_MPI-ESM-LR_Amon_historical_r2i1p1_tas_2000-2005.nc
/home/stef/esmvaltool_tutorial/esmvaltool_output/recipe_example_multi_preprocessors_3_20200811_090657/preproc/diag_variable_groups/tas_cmip5/CMIP5_CanESM2_Amon_historical_r1i1p1_tas_2000-2005.nc
2020-08-11 09:06:57,766 UTC [12788] INFO    Creating preprocessor task diag_variable_groups/tas_obs
2020-08-11 09:06:57,766 UTC [12788] INFO    Creating preprocessor 'prep_obs' task for variable 'tas'
2020-08-11 09:06:57,767 UTC [12788] WARNING Missing data for fx variable 'sftlf'
2020-08-11 09:06:57,768 UTC [12788] WARNING Missing data for fx variable 'sftof'
2020-08-11 09:06:57,768 UTC [12788] INFO    Using fx_files: {'sftlf': [], 'sftof': []} for variable tas during step mask_landsea
2020-08-11 09:06:57,768 UTC [12788] INFO    Using input files for variable tas of dataset HadCRUT4:

2020-08-11 09:06:57,768 UTC [12788] ERROR   No input files found for variable {'short_name': 'tas', 'preprocessor': 'prep_obs', 'mip': 'Amon', 'exp': 'historical', 'start_year': 2000, 'end_year': 2005, 'tag': 'TAS_OBS', 'variable_group': 'tas_obs', 'diagnostic': 'diag_variable_groups', 'dataset': 'HadCRUT4', 'project': 'OBS', 'type': 'ground', 'version': 1, 'tier': 2, 'recipe_dataset_index': 0, 'alias': 'OBS', 'standard_name': 'air_temperature', 'long_name': 'Near-Surface Air Temperature', 'units': 'K', 'modeling_realm': ['atmos'], 'frequency': 'mon'}
2020-08-11 09:06:57,768 UTC [12788] ERROR   Looked for files matching ['OBS_HadCRUT4_ground_1_Amon_tas[_.]*nc'], but did not find any existing input directory
2020-08-11 09:06:57,768 UTC [12788] ERROR   Set 'log_level' to 'debug' to get more information
2020-08-11 09:06:58,668 UTC [12788] INFO    Maximum memory used (estimate): 0.0 GB
2020-08-11 09:06:58,668 UTC [12788] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2020-08-11 09:06:58,669 UTC [12788] ERROR   Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 407, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_main.py", line 94, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 71, in read_recipe_file
    return Recipe(raw_recipe,
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 949, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 1297, in initialize_tasks
    task = _get_preprocessor_task(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 915, in _get_preprocessor_task
    task = _get_single_preprocessor_task(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 774, in _get_single_preprocessor_task
    products = _get_preprocessor_products(
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 740, in _get_preprocessor_products
    ancestors = _get_ancestors(variable, config_user)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe.py", line 552, in _get_ancestors
    check.data_availability(input_files, variable, dirnames, filenames)
  File "/home/stef/miniconda3/envs/esmvaltool/lib/python3.8/site-packages/esmvalcore/_recipe_checks.py", line 119, in data_availability
    raise RecipeError("Missing data")
esmvalcore._recipe_checks.RecipeError: Missing data
```

**Comment by SarahAlidoost** [comment]
@stefsmeets thanks. The error caused by missing data for projects `obs4mips` and `OBS`. PR #130 will fix this issue by adding a data link for `obs4mips` and removing `OBS`. The project `OBS` is related to using a cmorizer script that we skip it in the tutorial for now.
