### ISSUE TITLE
Recipe error when no variables provided

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#229]
In the episode on [Writing your own recipe](https://esmvalgroup.github.io/ESMValTool_Tutorial/06-preprocessor/index.html), we don't get a succesful run if we run the recipe without variables. At this time the tutorial suggests the run will be successful but that's not the case. ESMValTool actually produces an error message inclduing information that there were no tasks to run. 
Seems like this error message is in place so a user realizes they have forgotten to specify the variable.  This has to be changed in the lesson.

**Comment by remi-kazeroni** [comment]
Here is the type of error message obtained when running the variable-less recipe of the episode 6:
```bash
2022-02-10 15:47:02,359 UTC [21218] INFO    esmvalcore._recipe:1531 These tasks will be executed:
2022-02-10 15:47:02,360 UTC [21218] DEBUG   esmvalcore._main:122 Recipe summary:

2022-02-10 15:47:03,260 UTC [21218] INFO    esmvalcore._task:127 Maximum memory used (estimate): 0.0 GB
2022-02-10 15:47:03,261 UTC [21218] INFO    esmvalcore._task:129 Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2022-02-10 15:47:03,262 UTC [21218] ERROR   esmvalcore._main:484 No tasks to run!
2022-02-10 15:47:03,263 UTC [21218] DEBUG   esmvalcore._main:485 Stack trace for debugging:
Traceback (most recent call last):
  File "/work/bd0854/b309192/soft/miniconda3/envs/tool/lib/python3.10/site-packages/esmvalcore/_main.py", line 479, in run
    fire.Fire(ESMValTool())
  File "/work/bd0854/b309192/soft/miniconda3/envs/tool/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/work/bd0854/b309192/soft/miniconda3/envs/tool/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/work/bd0854/b309192/soft/miniconda3/envs/tool/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/work/bd0854/b309192/soft/miniconda3/envs/tool/lib/python3.10/site-packages/esmvalcore/_main.py", line 423, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/work/bd0854/b309192/soft/miniconda3/envs/tool/lib/python3.10/site-packages/esmvalcore/_main.py", line 125, in process_recipe
    recipe.run()
  File "/work/bd0854/b309192/soft/miniconda3/envs/tool/lib/python3.10/site-packages/esmvalcore/_recipe.py", line 1551, in run
    raise RecipeError('No tasks to run!')
esmvalcore.exceptions.RecipeError: No tasks to run!
```
